service: kachuful

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser
  region: eu-west-1
  environment:
    tableName: ${self:custom.tableName}
    IS_OFFLINE: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

custom:
  tableName: Kachuful
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

functions:
  websocket-connect:
    handler: lambdas/websockets/connect.handler
    events:
      - websocket:
          route: $connect
  websocket-disconnect:
    handler: lambdas/websockets/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  websocket-default:
    handler: lambdas/websockets/default.handler
    events:
      - websocket:
          route: $default
  websocket-message:
    handler: lambdas/websockets/message.handler
    events:
      - websocket:
          route: message
  websocket-getConnectionId:
    handler: lambdas/websockets/get-connection-id.handler
    events:
      - websocket:
          route: getConnectionId
  websocket-reCreateConnection:
    handler: lambdas/websockets/re-create-connection.handler
    events:
      - websocket:
          route: reCreateConnection
  websocket-refreshData:
    handler: lambdas/websockets/refresh-data.handler
    events:
      - websocket:
          route: refreshData
  websocket-sendName:
    handler: lambdas/websockets/send-name.handler
    events:
      - websocket:
          route: sendName
  websocket-distributeCards:
    handler: lambdas/websockets/distribute-cards.handler
    events:
      - websocket:
          route: distributeCards
  websocket-bidWins:
    handler: lambdas/websockets/bid-wins.handler
    events:
      - websocket:
          route: bidWins
  websocket-throwCard:
    handler: lambdas/websockets/throw-card.handler
    events:
      - websocket:
          route: throwCard
  websocket-finishRound:
    handler: lambdas/websockets/finish-round.handler
    events:
      - websocket:
          route: finishRound
  websocket-startGame:
    handler: lambdas/websockets/start-game.handler
    events:
      - websocket:
          route: startGame
  websocket-finishLevel:
    handler: lambdas/websockets/finish-level.handler
    events:
      - websocket:
          route: finishLevel
  websocket-endGame:
    handler: lambdas/websockets/end-game.handler
    events:
      - websocket:
          route: endGame

resources:
  Resources:
    WeboscketUserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-offline
  - serverless-dynamodb-local

package:
  exclude:
    - node_modules/**
    - .dynamodb/**
    - coverage/**
    - __tests__/**
