export const userMock = [
  {
    playerName: "Jimish",
    avatarLink: "",
    ID: 1,
    cardThrown: { type: "club", number: "2" },
    cardsInHand: [
      { type: "club", number: "J" },
      { type: "club", number: "K" },
    ],
    wins: { expectedWins: 99, currentWins: 99 },
    lastLevel: 3,
    cardsRemaining: 2,
    lastTrumpColour: "spade",
    sequenceNumber: 1,
    lastRoundWinner: true,
  },
  {
    playerName: "Sujana",
    avatarLink: "",
    ID: 2,
    cardsInHand: [
      { type: "club", number: "J" },
      { type: "club", number: "K" },
    ],
    wins: { expectedWins: 3, currentWins: 1 },
    lastLevel: 3,
    cardsRemaining: 2,
    lastTrumpColour: "spade",
    sequenceNumber: 2,
    lastRoundWinner: false,
  },
  {
    playerName: "Hardik",
    avatarLink: "",
    ID: 3,
    cardThrown: { type: "heart", number: "2" },
    cardsInHand: [
      { type: "club", number: "J" },
      { type: "club", number: "K" },
    ],
    wins: { expectedWins: 3, currentWins: 1 },
    lastLevel: 3,
    cardsRemaining: 2,
    lastTrumpColour: "spade",
    sequenceNumber: 3,
    lastRoundWinner: false,
  },
  {
    playerName: "Hiren",
    avatarLink: "",
    ID: 4,
    cardThrown: { type: "diamond", number: "2" },
    cardsInHand: [
      { type: "club", number: "J" },
      { type: "club", number: "K" },
    ],
    wins: { expectedWins: 3, currentWins: 2 },
    lastLevel: 3,
    cardsRemaining: 2,
    lastTrumpColour: "spade",
    sequenceNumber: 4,
    lastRoundWinner: false,
  },
  {
    playerName: "Malav",
    avatarLink: "",
    ID: 5,
    cardThrown: { type: "spade", number: "2" },
    cardsInHand: [
      { type: "club", number: "J" },
      { type: "club", number: "K" },
    ],
    wins: { expectedWins: 0, currentWins: 1 },
    lastLevel: 3,
    cardsRemaining: 2,
    lastTrumpColour: "spade",
    sequenceNumber: 5,
    lastRoundWinner: false,
  },
  {
    playerName: "Meghana",
    avatarLink: "",
    ID: 6,
    cardThrown: { type: "spade", number: "K" },
    cardsInHand: [
      { type: "club", number: "J" },
      { type: "club", number: "K" },
    ],
    wins: { expectedWins: 3, currentWins: 3 },
    lastLevel: 3,
    cardsRemaining: 2,
    lastTrumpColour: "spade",
    sequenceNumber: 6,
    lastRoundWinner: false,
  },
];
