const userMock = [
  {
    playerName: "Jimish",
    avatarLink: "",
    connectionID: 1,
    cardThrown: { type: "club", number: "2" },
    cardsInHand: [
      { type: "club", number: "J" },
      { type: "club", number: "K" },
    ],
    wins: { expectedWins: 3, currentWins: 1 },
    lastLevel: 3,
    cardsRemaining: 2,
    lastTrumpColour: "spade",
  },
  {
    playerName: "Sujana",
    avatarLink: "",
    connectionID: 2,
    cardsInHand: [
      { type: "club", number: "J" },
      { type: "club", number: "K" },
    ],
    wins: { expectedWins: 3, currentWins: 1 },
    lastLevel: 3,
    cardsRemaining: 2,
    lastTrumpColour: "spade",
  },
  {
    playerName: "Hardik",
    avatarLink: "",
    connectionID: 3,
    cardThrown: { type: "heart", number: "2" },
    cardsInHand: [
      { type: "club", number: "J" },
      { type: "club", number: "K" },
    ],
    wins: { expectedWins: 3, currentWins: 1 },
    lastLevel: 3,
    cardsRemaining: 2,
    lastTrumpColour: "spade",
  },
  {
    playerName: "Hiren",
    avatarLink: "",
    connectionID: 4,
    cardThrown: { type: "diamond", number: "2" },
    cardsInHand: [
      { type: "club", number: "J" },
      { type: "club", number: "K" },
    ],
    wins: { expectedWins: 3, currentWins: 2 },
    lastLevel: 3,
    cardsRemaining: 2,
    lastTrumpColour: "spade",
  },
  {
    playerName: "Malav",
    avatarLink: "",
    connectionID: 5,
    cardThrown: { type: "spade", number: "2" },
    cardsInHand: [
      { type: "club", number: "J" },
      { type: "club", number: "K" },
    ],
    wins: { expectedWins: 0, currentWins: 1 },
    lastLevel: 3,
    cardsRemaining: 2,
    lastTrumpColour: "spade",
  },
  {
    playerName: "Meghana",
    avatarLink: "",
    connectionID: 6,
    cardThrown: { type: "spade", number: "K" },
    cardsInHand: [
      { type: "club", number: "J" },
      { type: "club", number: "K" },
    ],
    wins: { expectedWins: 3, currentWins: 3 },
    lastLevel: 3,
    cardsRemaining: 2,
    lastTrumpColour: "spade",
  },
];
